
# Server
SMTP_SERVER_YAHOO = "smtp.mail.yahoo.com"
SMTP_SERVER = SMTP_SERVER_YAHOO


# Ports
SMTP_PORT_1 = 587
SMTP_PORT_2 = 465
SMTP_PORTS = (SMTP_PORT_1, SMTP_PORT_2)
SMTP_PORT = SMTP_PORT_1

# Files
CONFIG_FILE_NAME = 'config.ini'
